document.getElementById("blocktogglevnav").addEventListener("mouseenter", function(){showTextOnav(this, 'SIDEBAR')});
document.getElementById("blocktogglevnav").addEventListener("mouseleave", function(){hideTextOnav(this, 'SIDEBAR')});
document.getElementById("gotoindex").addEventListener("mouseenter", function(){showTextOnav(this, 'HOME')});
document.getElementById("gotoindex").addEventListener("mouseleave", function(){hideTextOnav(this, 'HOME')});
document.getElementById("gotowhoami").addEventListener("mouseenter", function(){showTextOnav(this, 'INFO')});
document.getElementById("gotowhoami").addEventListener("mouseleave", function(){hideTextOnav(this, 'INFO')});
document.getElementById("gotonews").addEventListener("mouseenter", function(){showTextOnav(this, 'NEWS')});
document.getElementById("gotonews").addEventListener("mouseleave", function(){hideTextOnav(this, 'NEWS')});
document.getElementById("gotoexperiments").addEventListener("mouseenter", function(){showTextOnav(this, 'TRY ME')});
document.getElementById("gotoexperiments").addEventListener("mouseleave", function(){hideTextOnav(this, 'TRY ME')});
